# Generated by Django 4.2.1 on 2023-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'uslugi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ZayavkiPolz',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('id_service', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'zayavki_polz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Polzovateli',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=30, unique=True)),
                ('manager', models.IntegerField(blank=True)),
                ('passport', models.IntegerField(blank=True, null=True)),
                ('fio', models.CharField(blank=True, db_column='FIO', max_length=80, null=True)),
                ('snils', models.IntegerField(blank=True, db_column='SNILS', null=True)),
                ('inn', models.IntegerField(blank=True, db_column='INN', null=True)),
                ('passport_whom', models.CharField(blank=True, db_column='passport_whom', max_length=80, null=True)),
                ('passport_code', models.CharField(blank=True, db_column='passport_code', max_length=80, null=True)),
                ('passport_data', models.CharField(blank=True, db_column='passport_data', max_length=80, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'polzovateli',
                'managed': True,
            },
        ),
    ]
